export const devData = [
  {
    id: 'booty',
    img: require('../assets/booty.png'),
    title: 'Booty or Death!',
    about: 'about the app here....',
    stack: 'tech stack here...',
    git: 'git link here...',
    deployed: 'deployed link here...',
  },
  {
    id: 'cooks',
    img: require('../assets/cooks.png'),
    title: 'CooksBooks',
    about: 'about the app here....',
    stack: 'tech stack here...',
    git: 'git link here...',
    deployed: 'deployed link here...',
  },
  {
    id: 'duet',
    img: require('../assets/duet.png'),
    title: 'Just Duet',
    about: 'about the app here....',
    stack: 'tech stack here...',
    git: 'git link here...',
    deployed: 'deployed link here...',
  },
  {
    id: 'sun',
    img: require('../assets/sun.png'),
    title: 'Sunshine',
    about: 'about the app here....',
    stack: 'tech stack here...',
    git: 'git link here...',
    deployed: 'deployed link here...',
  },
];