export const devData = [
  {
    id: 'booty',
    img: require('../assets/booty.png'),
    title: 'Booty or Death!',
    about: 'about the app here....',
    stack: 'Node, Inquirer, PostgreSQL, Express',
    git: 'https://github.com/PiratesOfAlchemy/booty-or-death',
    deployed:
      'https://www.npmjs.com/package/@pirates-of-alchemy/booty-or-death',
    imgArr: [
      require('../assets/booty.png'),
      require('../assets/booty2.png'),
      require('../assets/booty3.png'),
      require('../assets/booty4.png'),
      require('../assets/booty5.png'),
      require('../assets/booty6.png'),
      require('../assets/booty7.png'),
      require('../assets/booty8.png'),
    ],
  },
  {
    id: 'cooks',
    img: require('../assets/cooks.png'),
    title: 'CooksBooks',
    about: 'about the app here....',
    stack: 'React, HTML, CSS, PostgreSQL, Express',
    git: 'https://github.com/cookin-n-bookin',
    deployed: 'https://cooksbooks.netlify.app/books',
    imgArr: [
      require('../assets/cooks.png'),
      require('../assets/cooks2.png'),
      require('../assets/cooks3.png'),
      require('../assets/cooks4.png'),
    ],
  },
  {
    id: 'duet',
    img: require('../assets/duet.png'),
    title: 'Just Duet',
    about: 'about the app here....',
    stack: 'Vanilla JS, HTML, CSS, Supabase',
    git: 'https://github.com/Benatovich/just-duet',
    deployed: 'https://benatovich.github.io/just-duet/',
    imgArr: [
      require('../assets/duet.png'),
      require('../assets/duet2.png'),
      require('../assets/duet3.png'),
    ],
  },
  {
    id: 'sun',
    img: require('../assets/sun.png'),
    title: 'Sunshine',
    about: 'about the app here....',
    stack: 'React, HTML, CSS, Supabase',
    git: 'https://github.com/oliviaamiller/sunshine',
    deployed: 'https://sunshine2.netlify.app/',
    imgArr: [
      require('../assets/sun.png'),
      require('../assets/sun2.png'),
      require('../assets/sun3.png'),
      require('../assets/sun4.png'),
      require('../assets/sun5.png'),
    ],
  },
];
